import Navbar from "@/components/Navbar/Navbar";
import "@/app/globals.css";
import MenuBar from "@/components/Navbar/MenuBar";
import Footer from "@/components/Footer/Footer";
import { ReactNode } from "react";

export const metadata = {
    title: process.env.NEXT_PUBLIC_ENGLISH_TITLE,
    description: "Generated by Sifat",
};

interface FounderMessageLayoutProps {
    children: ReactNode;
}

export default function FounderMessageLayout({ children }: FounderMessageLayoutProps) {
    return (
        <section>
            <Navbar data-testid="nab" />
            <div style={{ position: "sticky", top: 0, width: "100%", zIndex: 50, transition: "ease-in-out" }}>
                <MenuBar />
            </div>
            <div className="max-w-7xl mx-auto">
                {children}
            </div>
            <Footer />
        </section>
    );
}
